#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : fortune-mod
Version  : 2.10.0
Release  : 7
URL      : https://www.shlomifish.org/open-source/projects/fortune-mod/arcs/fortune-mod-2.10.0.tar.xz
Source0  : https://www.shlomifish.org/open-source/projects/fortune-mod/arcs/fortune-mod-2.10.0.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-4-Clause
Requires: fortune-mod-bin = %{version}-%{release}
Requires: fortune-mod-man = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : recode-dev

%description
==================
This is fortune-mod. It now lives at:
* https://github.com/shlomif/fortune-mod

%package bin
Summary: bin components for the fortune-mod package.
Group: Binaries

%description bin
bin components for the fortune-mod package.


%package man
Summary: man components for the fortune-mod package.
Group: Default

%description man
man components for the fortune-mod package.


%prep
%setup -q -n fortune-mod-2.10.0
cd %{_builddir}/fortune-mod-2.10.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1581614614
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%cmake ..
make  %{?_smp_mflags}  VERBOSE=1
popd

%install
export SOURCE_DATE_EPOCH=1581614614
rm -rf %{buildroot}
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)
/usr/games/fortune

%files bin
%defattr(-,root,root,-)
/usr/bin/rot
/usr/bin/strfile
/usr/bin/unstr

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/strfile.1
/usr/share/man/man6/fortune.6
