#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : fortune-mod
Version  : 3.6.1
Release  : 12
URL      : https://www.shlomifish.org/open-source/projects/fortune-mod/arcs/fortune-mod-3.6.1.tar.xz
Source0  : https://www.shlomifish.org/open-source/projects/fortune-mod/arcs/fortune-mod-3.6.1.tar.xz
Summary  : Ad hoc headers library for C
Group    : Development/Tools
License  : BSD-4-Clause
Requires: fortune-mod-bin = %{version}-%{release}
Requires: fortune-mod-man = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : pkgconfig(cmocka)
BuildRequires : recode-dev
BuildRequires : rinutils

%description
==================
This is fortune-mod. It now lives at:
* https://github.com/shlomif/fortune-mod

%package bin
Summary: bin components for the fortune-mod package.
Group: Binaries

%description bin
bin components for the fortune-mod package.


%package man
Summary: man components for the fortune-mod package.
Group: Default

%description man
man components for the fortune-mod package.


%prep
%setup -q -n fortune-mod-3.6.1
cd %{_builddir}/fortune-mod-3.6.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1644854439
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1644854439
rm -rf %{buildroot}
pushd clr-build
%make_install
popd
## install_append content
mv %{buildroot}/usr/games/fortune %{buildroot}/usr/bin/fortune
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/fortune
/usr/bin/rot
/usr/bin/strfile
/usr/bin/unstr

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/strfile.1
/usr/share/man/man6/fortune.6
